import { useEffect, type FormEvent, type ReactNode } from 'react';
import { ArrowUpRight, Phone } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';

const siteUrl='https://www.redrosiba.lv';
function Meta({title,description}:{title:string;description:string}){const location=useLocation();useEffect(()=>{const url=`${siteUrl}${location.pathname}`;document.title=title;document.querySelector('meta[name="description"]')?.setAttribute('content',description);document.querySelector('meta[property="og:title"]')?.setAttribute('content',title);document.querySelector('meta[property="og:description"]')?.setAttribute('content',description);document.querySelector('meta[property="og:url"]')?.setAttribute('content',url);let canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=url},[title,description,location.pathname]);return null}
function Intro({label,title,children}:{label:string;title:ReactNode;children:ReactNode}){return <section className="page-intro"><p className="eyebrow">{label}</p><h1>{title}</h1><p>{children}</p></section>}
function ContactPage(){const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);window.location.href=`mailto:pasts@redrosiba.lv?subject=Konfidenciālas konsultācijas pieprasījums&body=Vārds: ${d.get('name')}%0AUzņēmums: ${d.get('company')}%0ATālrunis: ${d.get('phone')}%0A%0A${d.get('message')}`};return <><Meta title="Kontakti — RE Drošība" description="Sazinieties ar RE Drošība, lai konfidenciāli pārrunātu uzņēmuma iekšējās drošības riskus."/><Intro label="SĀKSIM SARUNU" title={<>Parunāsim par to,<br/><em>kas notiek iekšienē.</em></>}>Aprakstiet situāciju — mēs sazināsimies konfidenciālai, neuzbāzīgai sarunai.</Intro><section className="contact contact-page"><div className="contact-intro"><p className="eyebrow">TIEŠI KONTAKTI</p><h2>Diskrēta saruna<br/><em>sākas šeit.</em></h2><div className="contact-details"><a href="tel:+37126116877"><Phone size={18}/>26 116 877</a><a href="mailto:pasts@redrosiba.lv">pasts@redrosiba.lv</a><a href="https://www.redrosiba.lv">www.redrosiba.lv</a></div><p>Visa saņemtā informācija tiek izmantota tikai saziņai par jūsu pieprasījumu.</p></div><form onSubmit={submit}><label>Jūsu vārds<input name="name" required placeholder="Vārds, uzvārds"/></label><label>Uzņēmums<input name="company" placeholder="Uzņēmuma nosaukums"/></label><label>Tālrunis<input name="phone" required type="tel" placeholder="+371 ..."/></label><label>Īss situācijas apraksts<textarea name="message" rows={4} placeholder="Ar ko varam palīdzēt?"></textarea></label><button className="button" type="submit">Nosūtīt pieprasījumu <ArrowUpRight size={18}/></button></form></section></>}
export default ContactPage;
