import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import '../test.css';
import '../compact-result.css';
import '../result-readability.css';

export const TEST_STORAGE_KEY = 're-drosiba-security-test';
const answerLabels = ['Jā, vienmēr', 'Daļēji vai ne vienmēr', 'Nē', 'Nezinu'];
const options = answerLabels.map((label, index) => ({ label, points: index === 0 ? 0 : index === 1 ? 2 : 3 }));
export const questions = [
  { id: 'access', zone: 'Piekļuve resursiem', text: 'Vai jūs zināt, kam uzņēmumā ir pieeja precēm, naudai, noliktavai, sistēmām un datiem?', advice: 'Pārbaudiet, kam ir pieeja uzņēmuma precēm, naudai un datiem.' },
  { id: 'separation', zone: 'Pienākumu sadalījums', text: 'Vai svarīgus darbus vienmēr pārbauda vēl kāds cits, nevis tikai viena persona?', advice: 'Svarīgus darbus ieteicams pārbaudīt vēl vienai personai.' },
  { id: 'discrepancies', zone: 'Iztrūkumu pārbaude', text: 'Vai uzņēmumā tiek noskaidrots, kāpēc rodas iztrūkumi vai citas neatbilstības?', advice: 'Nosakiet, kas fiksē iztrūkumu, kas to pārbauda un kā tiek noskaidrots iemesls.' },
  { id: 'procedures', zone: 'Noteikumu ievērošana', text: 'Vai tiek pārbaudīts, vai darbinieki ikdienā ievēro uzņēmuma noteikumus?', advice: 'Salīdziniet uzņēmuma noteikumus ar to, kas notiek ikdienā.' },
  { id: 'review', zone: 'Neatkarīga pārbaude', text: 'Vai pēdējā gada laikā kāds no malas ir pārbaudījis jūsu uzņēmuma iekšējos procesus?', advice: 'Neatkarīga pārbaude palīdz pamanīt riskus, kurus ikdienā var nepamanīt.' },
];
export type TestData = { answers: number[]; score: number; level: string; levelText: string; details: { zone: string; question: string; answer: string; points: number; advice: string }[]; priorities: string[] };
export function getResult(answers: number[]): TestData { const details = questions.map((q, i) => { const points = options[answers[i]]?.points ?? 0; return { zone: q.zone, question: q.text, answer: answerLabels[answers[i]] ?? '', points, advice: q.advice }; }); const score = details.reduce((sum, item) => sum + item.points, 0); const result = score <= 4 ? { level: 'Zemāks identificētais risks', levelText: 'Kontroles pamati, visticamāk, ir ieviesti, taču tos ieteicams regulāri pārbaudīt arī ikdienas darbībā.' } : score <= 9 ? { level: 'Paaugstināts identificētais risks', levelText: 'Vairākos kritiskos posmos kontrole vai pārskatāmība var nebūt pietiekama.' } : { level: 'Augsts identificētais risks', levelText: 'Uzņēmuma procesos var būt būtiskas ievainojamības, kuras būtu lietderīgi pārbaudīt prioritārā kārtā.' }; return { answers, score, ...result, details, priorities: details.filter(item => item.points === 3).map(item => item.zone) }; }
function PlainResultSummary({ result }: { result: TestData }) { const high = result.details.filter(item => item.points === 3); const partial = result.details.filter(item => item.points === 2); const good = result.details.filter(item => item.points === 0); return <div className="plain-summary"><p>Jūsu atbildes rāda, ka visvairāk uzmanības nepieciešams pievērst {high.length + partial.length ? `šīm ${high.length + partial.length} jomām` : 'kontroles uzturēšanai'}:</p>{high.map(item => <p className="summary-item" key={item.zone}><strong>{item.zone}.</strong> {item.zone === 'Piekļuves kontrole' ? 'Pārbaudiet, kam ir pieeja precēm, naudai, noliktavām un datiem.' : item.zone === 'Procedūru ievērošana' ? 'Pārliecinieties, vai darbinieki ikdienā tiešām ievēro uzņēmuma noteikumus.' : item.zone === 'Neatkarīga pārbaude' ? 'Plānojiet neatkarīgu drošības pārbaudi, lai pamanītu riskus no malas.' : item.advice}</p>)}{partial.map(item => <p className="summary-item" key={item.zone}><strong>{item.zone}.</strong> {item.zone === 'Iztrūkumu kontrole' ? 'Izveidojiet skaidru kārtību: kas iztrūkumu fiksē, kas to pārbauda un kā noskaidro iemeslu.' : item.advice}</p>)}{good.length > 0 && <p className="summary-positive"><strong>Kontrole darbojas:</strong> {good.map(item => item.zone.toLowerCase()).join(', ')}. Šo kārtību ieteicams regulāri pārbaudīt un uzturēt.</p>}{result.priorities.length > 0 && <p className="summary-priority"><strong>Svarīgāk pārbaudīt vispirms:</strong> {result.priorities.join(', ')}.</p>}</div> }
function SecurityTestPage() { const navigate = useNavigate(); const [step, setStep] = useState(0); const [answers, setAnswers] = useState<number[]>([]); const result = getResult(answers); const choose = (index: number) => { const next = [...answers]; next[step] = index; setAnswers(next); }; const finish = () => { const finalResult = getResult(answers); sessionStorage.setItem(TEST_STORAGE_KEY, JSON.stringify(finalResult)); setStep(questions.length); }; return <section className="security-test">
    {step < questions.length && <div className="test-card"><div className="test-progress"><span>Jautājums {step + 1} no 5</span><span>{Math.round(((step + 1) / 5) * 100)}%</span></div><div className="progress-track"><span style={{ width: `${((step + 1) / 5) * 100}%` }} /></div><fieldset><legend>{questions[step].text}</legend><div className="answer-list">{options.map((option, index) => <label className={answers[step] === index ? 'selected' : ''} key={option.label}><input type="radio" name={`question-${step}`} checked={answers[step] === index} onChange={() => choose(index)} />{option.label}</label>)}</div></fieldset><div className="test-actions">{step > 0 && <button type="button" className="button secondary" onClick={() => setStep(step - 1)}><ArrowLeft size={18} /> Atpakaļ</button>}<button type="button" className="button" disabled={answers[step] === undefined} onClick={() => step < 4 ? setStep(step + 1) : finish()}>{step < 4 ? 'Turpināt' : 'Skatīt rezultātu'} <ArrowUpRight size={18} /></button></div></div>}
    {step === 5 && <div className="test-result"><p className="eyebrow">JŪSU REZULTĀTS</p><h1>{result.level}</h1><p className="result-score">{result.score} no 15 punktiem</p><p className="result-lead">{result.levelText}</p><div className="result-section"><h2>Riska zonas</h2><div className="result-details">{result.details.map(item => <p className={item.points === 3 ? 'risk-line' : ''} key={item.zone}><strong>{item.zone}</strong> — {item.answer}. {item.points > 0 ? item.advice : 'Kontrole identificēta — turpiniet to regulāri pārbaudīt.'}</p>)}</div>{result.priorities.length > 0 && <p className="priority-summary"><strong>Būtiskākie riska signāli:</strong> {result.priorities.join(', ')}.</p>}</div><div className="result-section result-meaning"><h2>Ko tas nozīmē jūsu uzņēmumam?</h2><p>Šis pašnovērtējums palīdz pamanīt, kuros procesos var būt nepieciešama lielāka pārskatāmība. RE Drošība var palīdzēt pārbaudīt piekļuves punktus, procesu faktisko norisi un iespējamos zaudējumu cēloņus diskrēti un sistemātiski.</p><p>Praktiska neatkarīga pārbaude ļauj vadībai balstīties uz faktiem un saprast, kur nepieciešamas izmaiņas, lai kontroles darbotos ikdienā.</p></div><p className="test-disclaimer">Šis ir informatīvs pašnovērtējums, nevis profesionālas drošības pārbaudes slēdziens.</p><button className="button" onClick={() => navigate('/kontakti')}>Pārrunāt testa rezultātu konfidenciālā sarunā <ArrowUpRight size={18} /></button><Link className="test-restart" to="/drošibas-tests" onClick={() => { sessionStorage.removeItem(TEST_STORAGE_KEY); setStep(0); setAnswers([]); }}>Aizpildīt vēlreiz</Link></div>}
  </section>; }
export default SecurityTestPage;
