import { StrictMode, type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, Check, ChevronDown, Eye, Fingerprint, LockKeyhole, Menu, Network, Phone, Search, ShieldCheck, X } from 'lucide-react';
import './styles.css';

const services = ['Noliktavas un loģistikas centri','Ražotnes un preču aprites uzņēmumi','Uzņēmumi ar regulāriem iztrūkumiem','Uzņēmumi ar lielu darbinieku kolektīvu'];
const steps = [{ icon: Search, title: 'Diskrēta izpēte', text: 'Iepazīstam uzņēmuma procesus un vienojamies par pārbaudes mērķi.' }, { icon: Fingerprint, title: 'Integrēšanās kolektīvā', text: 'Mūsu speciālists veic iepriekš saskaņotu darba lomu ikdienas vidē.' }, { icon: Eye, title: 'Faktu apkopošana', text: 'Novērojam procesus, analizējam riskus un pārbaudām iespējamās ķēdes.' }, { icon: Network, title: 'Detalizēts ziņojums', text: 'Vadība saņem objektīvu, konfidenciālu informāciju un ieteikumus.' }];

function App() {
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); window.location.href = `mailto:pasts@redrosiba.lv?subject=Konfidenciālas konsultācijas pieprasījums&body=Vārds: ${data.get('name')}%0AUzņēmums: ${data.get('company')}%0ATālrunis: ${data.get('phone')}%0A%0A${data.get('message')}`; };
  return <><header className="nav"><a className="logo" href="#sakums"><span className="logo-mark">R<span>E</span></span><span>RE <b>DROŠĪBA</b></span></a><nav><a href="#pakalpojums">Pakalpojums</a><a href="#process">Kā tas darbojas</a><a href="#par-mums">Par mums</a></nav><a href="#kontakti" className="nav-cta">Sazināties <ArrowUpRight size={16}/></a><button className="menu" aria-label="Atvērt izvēlni"><Menu/></button></header>
  <main><section id="sakums" className="hero"><div className="hero-copy"><p className="eyebrow">IEKŠĒJĀS DROŠĪBAS IZPĒTE</p><h1>Mēs atrodam to,<br/><em>ko citi neredz.</em></h1><p className="lead">Konfidenciāla uzņēmuma iekšējās vides pārbaude, lai identificētu preču iztrūkumu cēloņus, drošības riskus un iespējamās zādzību ķēdes.</p><a className="button" href="#kontakti">Pieteikt konsultāciju <ArrowUpRight size={18}/></a><div className="hero-note"><LockKeyhole size={18}/><span>Konfidenciāli. Objektīvi. Pēc vienošanās.</span></div></div><div className="hero-visual"><img src="/hero-reference.jpeg" alt="RE Drošība speciālists uzņēmuma iekšējā vidē"/><div className="visual-tag"><span>01</span> Iekšējā izpēte</div></div></section>
  <section className="stats"><div><strong>12</strong><span>gadi praktiskas<br/>pieredzes</span></div><div><strong>100%</strong><span>konfidenciāla<br/>pieeja</span></div><div><strong>LV</strong><span>specializēts<br/>pakalpojums Latvijā</span></div></section>
  <section id="pakalpojums" className="section split"><div><p className="eyebrow">KĀPĒC TAS IR VAJADZĪGS?</p><h2>Atbilde bieži<br/><em>slēpjas iekšienē.</em></h2></div><div className="section-text"><p>Videonovērošana, apsardze un inventarizācijas palīdz sargāt uzņēmumu. Tomēr problēma var atrasties starp ikdienas darba procesiem un cilvēkiem, kuri tos vislabāk pārzina.</p><p>Tieši tādēļ mēs skatāmies uz drošību no otras puses — ar reālu klātbūtni uzņēmuma iekšējā vidē.</p></div></section>
  <section id="process" className="dark-section"><div className="section-heading"><div><p className="eyebrow">MŪSU PIEEJA</p><h2>Kā tas <em>darbojas?</em></h2></div><p>Mērķis nav izdarīt pieņēmumus. Mērķis ir pārbaudīt faktus un palīdzēt vadībai pieņemt pamatotus lēmumus.</p></div><div className="step-grid">{steps.map(({icon: Icon,title,text},i)=><article className="step" key={title}><span className="step-number">0{i+1}</span><Icon className="step-icon"/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section questions"><div><p className="eyebrow">MĒRĶIS</p><h2>Kur pazūd<br/><em>jūsu preces?</em></h2><p className="section-text">Mēs palīdzam noskaidrot, kas notiek starp uzņēmuma procesiem — diskrēti, sistemātiski un ar cieņu pret visām iesaistītajām pusēm.</p></div><div className="question-list">{['Kurā posmā rodas iztrūkums?','Kādi riski pastāv ikdienas procesos?','Kā darbojas iespējamā zādzību ķēde?','Kā novērst līdzīgas situācijas nākotnē?'].map(q=><div key={q}><Check size={18}/><span>{q}</span></div>)}</div></section>
  <section id="par-mums" className="audience"><div className="audience-copy"><p className="eyebrow">KAM MĒS PALĪDZAM?</p><h2>Jūsu darbība.<br/><em>Mūsu skatiens.</em></h2><p>Īpaši uzņēmumiem, kuros ir liela preču aprite, vairāki noliktavas vai transporta posmi un regulāri iztrūkumi.</p></div><div className="audience-list">{services.map((s,i)=><div key={s}><span>0{i+1}</span>{s}<ArrowUpRight size={18}/></div>)}</div></section>
  <section className="trust"><ShieldCheck size={42}/><div><p className="eyebrow">JAUNS UZŅĒMUMS. PIEREDZĒJUSI PIEEJA.</p><h2>Drošība sākas ar patiesu izpratni.</h2><p>Esam jauns, specializēts uzņēmums, kura pamatā ir 12 gadu praktiska pieredze apsardzes jomā. Mēs apzināti neveidojam kārtējo tradicionālo apsardzes uzņēmumu.</p></div></section>
  <section id="kontakti" className="contact"><div className="contact-intro"><p className="eyebrow">SĀKSIM SARUNU</p><h2>Parunāsim par to,<br/><em>kas notiek iekšienē.</em></h2><p>Aprakstiet situāciju — mēs sazināsimies konfidenciālai, neuzbāzīgai sarunai.</p><div className="contact-details"><a href="tel:+37126116877"><Phone size={18}/>26 116 877</a><a href="mailto:pasts@redrosiba.lv">pasts@redrosiba.lv</a></div></div><form onSubmit={submit}><label>Jūsu vārds<input name="name" required placeholder="Vārds, uzvārds"/></label><label>Uzņēmums<input name="company" placeholder="Uzņēmuma nosaukums"/></label><label>Tālrunis<input name="phone" required type="tel" placeholder="+371 ..."/></label><label>Īss situācijas apraksts<textarea name="message" rows={4} placeholder="Ar ko varam palīdzēt?"></textarea></label><button className="button" type="submit">Nosūtīt pieprasījumu <ArrowUpRight size={18}/></button></form></section></main>
  <footer><a className="logo" href="#sakums"><span className="logo-mark">R<span>E</span></span><span>RE <b>DROŠĪBA</b></span></a><p>IEKŠĒJĀS DROŠĪBAS IZPĒTE<br/>UN ZAUDĒJUMU NOVĒRŠANA</p><div><a href="#kontakti">Kontakti</a><a href="#privatums">Privātums</a></div><small id="privatums">© 2026 RE Drošība. Informācija ir informatīva un neaizstāj juridisku konsultāciju.</small></footer></>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
